# Generated by Django 3.2.6 on 2021-09-25 11:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
